# -*- coding: utf-8 -*-
"""Build dist/OpenOfficeAI-<version>.oxt from the extension/ folder.

Addons.xcu (toolbar and menu) and description.xml are generated here, so the
labels come from the same i18n table the Python code uses.

    python build.py
"""
from __future__ import unicode_literals

import os
import sys
import zipfile
from xml.sax.saxutils import escape

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "extension")
DIST = os.path.join(ROOT, "dist")
sys.path.insert(0, os.path.join(SRC, "pythonpath"))

from openofficeai import VERSION, i18n, prompts  # noqa: E402

EXTENSION_ID = "org.openofficeai.extension"
PROTOCOL = "org.openofficeai:"
CONTEXT = "com.sun.star.text.TextDocument"
# Office locale codes for the xml:lang attribute.
XML_LANG = {"it": "it", "en": "en-US", "es": "es", "fr": "fr", "de": "de"}
MENU_TITLE = {"it": "AI", "en": "AI", "es": "IA", "fr": "IA", "de": "KI"}
COMMANDS = [a.key for a in prompts.ACTIONS] + ["settings"]


def localized(values):
    return "".join('<value xml:lang="{0}">{1}</value>'.format(XML_LANG[lang], escape(values[lang]))
                   for lang in i18n.LANGUAGES)


def label(command):
    return dict((lang, i18n.STRINGS[lang]["act." + command]) for lang in i18n.LANGUAGES)


def prop(name, inner):
    return '<prop oor:name="{0}" oor:type="xs:string">{1}</prop>'.format(name, inner)


def value(text):
    return "<value>{0}</value>".format(escape(text))


def item(node, command):
    return ('<node oor:name="{0}" oor:op="replace">{1}{2}{3}{4}</node>'.format(
        node,
        prop("URL", value(PROTOCOL + command)),
        prop("Title", localized(label(command))),
        prop("Target", value("_self")),
        prop("Context", value(CONTEXT))))


def separator(node):
    return '<node oor:name="{0}" oor:op="replace">{1}</node>'.format(
        node, prop("URL", value("private:separator")))


def addons_xcu():
    toolbar = "".join(item("t{0:02d}".format(i), c) for i, c in enumerate(COMMANDS, 1))
    menu = [item("m{0:02d}".format(i), c) for i, c in enumerate(COMMANDS[:-1], 1)]
    menu.append(separator("m{0:02d}".format(len(COMMANDS))))
    menu.append(item("m{0:02d}".format(len(COMMANDS) + 1), "settings"))
    images = "".join(
        '<node oor:name="org.openofficeai.image.{0}" oor:op="replace">{1}'
        '<node oor:name="UserDefinedImages">{2}{3}</node></node>'.format(
            c, prop("URL", value(PROTOCOL + c)),
            prop("ImageSmallURL", value("%origin%/icons/{0}_16.png".format(c))),
            prop("ImageBigURL", value("%origin%/icons/{0}_26.png".format(c))))
        for c in COMMANDS)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by build.py from extension/pythonpath/openofficeai/i18n.py -->\n'
        '<oor:component-data xmlns:oor="http://openoffice.org/2001/registry" '
        'xmlns:xs="http://www.w3.org/2001/XMLSchema" oor:name="Addons" oor:package="org.openoffice.Office">'
        '<node oor:name="AddonUI">'
        '<node oor:name="OfficeMenuBar">'
        '<node oor:name="org.openofficeai.menu" oor:op="replace">'
        + prop("Title", localized(MENU_TITLE)) + prop("Context", value(CONTEXT)) +
        '<node oor:name="Submenu">' + "".join(menu) + '</node>'
        '</node></node>'
        '<node oor:name="OfficeToolBar">'
        '<node oor:name="org.openofficeai.toolbar" oor:op="replace">'
        + prop("Title", localized(dict((lang, "OpenOfficeAI") for lang in i18n.LANGUAGES))) +
        '<node oor:name="ToolBarItems">' + toolbar + '</node>'
        '</node></node>'
        '<node oor:name="Images">' + images + '</node>'
        '</node></oor:component-data>\n')


def description_xml():
    names = "".join('<name lang="{0}">OpenOfficeAI</name>'.format(lang) for lang in i18n.LANGUAGES)
    descs = "".join('<src lang="{0}" xlink:href="description/desc_{0}.txt"/>'.format(lang)
                    for lang in i18n.LANGUAGES)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<description xmlns="http://openoffice.org/extensions/description/2006" '
        'xmlns:d="http://openoffice.org/extensions/description/2006" '
        'xmlns:xlink="http://www.w3.org/1999/xlink">\n'
        '  <identifier value="{id}"/>\n'
        '  <version value="{version}"/>\n'
        '  <dependencies><OpenOffice.org-minimal-version value="3.4" d:name="OpenOffice.org 3.4"/></dependencies>\n'
        '  <display-name>{names}</display-name>\n'
        '  <publisher><name xlink:href="https://github.com/ShinRalexis/OpenOfficeAI" lang="en">MetaDarko</name></publisher>\n'
        '  <extension-description>{descs}</extension-description>\n'
        '  <icon><default xlink:href="icons/extension.png"/></icon>\n'
        '</description>\n').format(id=EXTENSION_ID, version=VERSION, names=names, descs=descs)


def source_files():
    for folder, dirs, files in os.walk(SRC):
        dirs[:] = [d for d in dirs if d != "__pycache__"]
        for name in sorted(files):
            if name.endswith((".pyc", ".pyo")):
                continue
            full = os.path.join(folder, name)
            yield full, os.path.relpath(full, SRC).replace(os.sep, "/")


def build():
    if not os.path.isdir(DIST):
        os.makedirs(DIST)
    target = os.path.join(DIST, "OpenOfficeAI-{0}.oxt".format(VERSION))
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as z:
        for full, arc in source_files():
            z.write(full, arc)
        z.writestr("Addons.xcu", addons_xcu().encode("utf-8"))
        z.writestr("description.xml", description_xml().encode("utf-8"))
    return target


if __name__ == "__main__":
    print(build())
